### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [MisterHW/LEDCard#1]
Hello!

I found this project from https://hackaday.com/2023/01/01/ledcard-the-pocketable-ring-light/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code and PCB files in any purpose? (except of `doc` directory, I think).
It would be great to see any popular open source license.

**Comment by MisterHW** [comment]
Hello,

I've added OHL-S v2 license information. The supplemental documents are obviously not my work but added for educational purposes as differences between these parts are discussed and the reader is expected to need to look them up, which should be covered under fair use (plus, I'm as tired as everyone to continuously go and hunt down datasheets and errata). 
As a pro-forma statement, the reader should also check the manufacturers' websites for the latest version of the documents. 

Issue resolved though https://github.com/MisterHW/LEDCard/commit/1b5f86fcf28a68698b8123f808d86395ac07e062
